import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  parseSecretOutput,
  CommandSecretsProvider,
  unquoteDotenvValue,
} from "./commandProvider";

// getConfigValue is the only config dependency of the command provider; mock it
// so the tests don't touch a real config.yaml.
vi.mock("../config", () => ({
  getConfigValue: vi.fn(),
}));
import { getConfigValue } from "../config";

const mockedGetConfigValue = vi.mocked(getConfigValue);

describe("parseSecretOutput", () => {
  it("returns a bare value (single-secret helper)", () => {
    expect(parseSecretOutput("hunter2\n", "ANYTHING")).toBe("hunter2");
  });

  it("trims surrounding whitespace/newlines from a bare value", () => {
    expect(parseSecretOutput("  s3cr3t  \n\n", "K")).toBe("s3cr3t");
  });

  it("returns null for empty output", () => {
    expect(parseSecretOutput("", "K")).toBeNull();
    expect(parseSecretOutput("   \n  ", "K")).toBeNull();
  });

  it("parses a dotenv blob and returns the requested key", () => {
    const blob = "API_SERVER_KEY=abc123\nANTHROPIC_TOKEN=sk-xyz\n";
    expect(parseSecretOutput(blob, "ANTHROPIC_TOKEN")).toBe("sk-xyz");
    expect(parseSecretOutput(blob, "API_SERVER_KEY")).toBe("abc123");
  });

  it("returns null when a dotenv blob lacks the requested key", () => {
    expect(parseSecretOutput("FOO=1\nBAR=2\n", "MISSING")).toBeNull();
  });

  it("strips surrounding quotes from dotenv values", () => {
    expect(parseSecretOutput('K="quoted value"\n', "K")).toBe("quoted value");
    expect(parseSecretOutput("K='single'\n", "K")).toBe("single");
  });

  it("ignores comments and blank lines in a dotenv blob", () => {
    const blob = "# a comment\n\nK=v\n";
    expect(parseSecretOutput(blob, "K")).toBe("v");
  });

  it("handles CRLF line endings", () => {
    expect(parseSecretOutput("K=v\r\nJ=w\r\n", "J")).toBe("w");
  });

  it("returns null (not a wrong value) when a multi-key dump lacks the wanted key", () => {
    // Regression: the old greedy heuristic could mis-handle this. A dump with
    // other KEY=VALUE lines but not ours must resolve to null, never another
    // line's value.
    const blob = "FOO=secretfoo\nBAR=secretbar\n";
    expect(parseSecretOutput(blob, "ANTHROPIC_TOKEN")).toBeNull();
  });

  it("prefers an exact dotenv match over treating output as a bare value", () => {
    const blob = "OTHER=x\nANTHROPIC_TOKEN=right\n";
    expect(parseSecretOutput(blob, "ANTHROPIC_TOKEN")).toBe("right");
  });

  it("treats single-line output with no '=' as a bare value", () => {
    expect(parseSecretOutput("just-the-secret\n", "ANY")).toBe(
      "just-the-secret",
    );
  });

  it("round-trips a bare base64 secret with '=' padding", () => {
    // Regression: "dGVzdA==" matches the KEY=VALUE shape (key "dGVzdA",
    // value "="), so a single env-shaped line used to be misclassified as a
    // one-line dotenv dump lacking the wanted key and resolved to null.
    expect(parseSecretOutput("dGVzdA==\n", "ANTHROPIC_API_KEY")).toBe(
      "dGVzdA==",
    );
  });

  it("S2: a single NON-matching env-shaped line is a misroute, not a bare value", () => {
    // SECURITY regression (S2): a helper that emits `OTHER_KEY=realvalue`
    // (e.g. `head -1 env-file`, a wrong grep) must NOT have that line
    // returned as the wanted secret — that is cross-key credential leakage
    // into the wanted key's destination. Supersedes the old behavior that
    // returned the whole line as a bare value.
    expect(parseSecretOutput("abc=def\n", "WANTED_KEY")).toBeNull();
    expect(
      parseSecretOutput("ANTHROPIC_TOKEN=***\n", "API_SERVER_KEY"),
    ).toBeNull();
  });

  it("S2: a COMMENT before a single wrong-key line is still a misroute (Greptile #644)", () => {
    // SECURITY regression: keepassxc-cli / secret-tool emit a header comment.
    // With `# comment\nOTHER_KEY=secret`, the comment-stripped extraction has
    // exactly one env line — but the full trimmed text starts with `#`, so the
    // old guard (matching the FULL text against ^-anchored ENV_LINE) returned
    // null and leaked the whole comment+wrong-key string as the bare value.
    // The guard now tests the extracted dotenv line, so this resolves to null.
    expect(
      parseSecretOutput(
        "# Generated by keepassxc-cli\nOTHER_KEY=secretvalue\n",
        "WANTED_KEY",
      ),
    ).toBeNull();
    expect(
      parseSecretOutput(
        "# vault dump\nANTHROPIC_TOKEN=sk-ant-leak\n",
        "API_SERVER_KEY",
      ),
    ).toBeNull();
  });

  it("S2: a COMMENT before the MATCHING key still resolves (comment is not fatal)", () => {
    // The comment-line handling must not break the legitimate case: a header
    // comment followed by the wanted key resolves via the dotenv branch.
    expect(
      parseSecretOutput(
        "# Generated by keepassxc-cli\nWANTED_KEY=value123\n",
        "WANTED_KEY",
      ),
    ).toBe("value123");
  });

  it("S2: base64 padding is still a bare value (not misclassified as a misroute)", () => {
    // The misroute rule keys on a NON-trivial value part; base64 padding
    // yields value parts that are empty or all '=' and stays a bare secret.
    expect(parseSecretOutput("dGVzdA==\n", "ANY")).toBe("dGVzdA==");
    expect(parseSecretOutput("c2VjcmV0=\n", "ANY")).toBe("c2VjcmV0=");
  });

  it("S2: a single MATCHING env-shaped line still resolves via the dotenv branch", () => {
    expect(parseSecretOutput("WANTED_KEY=value123\n", "WANTED_KEY")).toBe(
      "value123",
    );
  });

  it("still treats >=2 env-shaped lines lacking the wanted key as a dump (null)", () => {
    expect(parseSecretOutput("FOO=1\nBAR=2\n", "WANTED_KEY")).toBeNull();
  });
});

describe("parseSecretOutput whitespace-only values (V3)", () => {
  it("returns null for whitespace-only bare output", () => {
    expect(parseSecretOutput(" \n", "K")).toBeNull();
  });

  it("returns null for tab-only bare output", () => {
    expect(parseSecretOutput("\t\n", "K")).toBeNull();
  });

  it("trims leading/trailing whitespace but preserves the value", () => {
    expect(parseSecretOutput("  actual-secret  \n", "K")).toBe("actual-secret");
  });

  it("returns null for a quoted whitespace-only dotenv value", () => {
    // `K="  "` unquotes to whitespace, which previously survived the
    // empty-check (`value !== ""`) and looked like a valid key.
    expect(parseSecretOutput('K="   "\n', "K")).toBeNull();
    expect(parseSecretOutput("K='\t'\n", "K")).toBeNull();
  });
});

describe("unquoteDotenvValue", () => {
  it("strips matching double and single quotes", () => {
    expect(unquoteDotenvValue('"value"')).toBe("value");
    expect(unquoteDotenvValue("'value'")).toBe("value");
  });

  it("yields empty string for empty quote pairs", () => {
    expect(unquoteDotenvValue('""')).toBe("");
    expect(unquoteDotenvValue("''")).toBe("");
  });

  it("leaves a lone quote intact (does not collapse to empty)", () => {
    // Regression: a length<2 guard prevents a single quote char from being
    // sliced into the empty string.
    expect(unquoteDotenvValue('"')).toBe('"');
    expect(unquoteDotenvValue("'")).toBe("'");
  });

  it("does not strip mismatched or partial quotes", () => {
    expect(unquoteDotenvValue("\"value'")).toBe("\"value'");
    expect(unquoteDotenvValue('value"')).toBe('value"');
    expect(unquoteDotenvValue('"unterminated')).toBe('"unterminated');
  });

  it("trims surrounding whitespace before considering quotes", () => {
    expect(unquoteDotenvValue('  "padded"  ')).toBe("padded");
  });
});

describe("CommandSecretsProvider", () => {
  if (process.platform === "win32") {
    it("is POSIX-only and is covered by integration tests on non-Windows hosts", () => {
      expect(process.platform).toBe("win32");
    });
    return;
  }

  const provider = new CommandSecretsProvider();

  beforeEach(() => {
    mockedGetConfigValue.mockReset();
  });
  afterEach(() => {
    delete process.env.HERMES_TEST_MARKER;
  });

  it("returns null when no command is configured", () => {
    mockedGetConfigValue.mockReturnValue(null);
    expect(provider.get("ANY_KEY")).toBeNull();
  });

  it("runs the configured command and returns its bare-value stdout", () => {
    mockedGetConfigValue.mockReturnValue("printf 'resolved-value'");
    expect(provider.get("SOME_KEY")).toBe("resolved-value");
  });

  it("passes the requested key via $HERMES_SECRET_KEY, not the shell string", () => {
    // The command echoes the env var; if the key were interpolated into the
    // command string this would differ. It must arrive as data via the env.
    mockedGetConfigValue.mockReturnValue('printf "%s" "$HERMES_SECRET_KEY"');
    expect(provider.get("MY_LOOKUP_KEY")).toBe("MY_LOOKUP_KEY");
  });

  it("is injection-safe: a hostile key name cannot execute", () => {
    // If the key were interpolated into the shell, this would try to run `id`.
    // Because it's passed as data, the command just echoes the literal string.
    mockedGetConfigValue.mockReturnValue('printf "%s" "$HERMES_SECRET_KEY"');
    const hostile = '"; id; echo "';
    expect(provider.get(hostile)).toBe(hostile);
  });

  it("does not let a hostile key name run a side-effect command", () => {
    // A command that would only set the marker if the injected payload executed.
    mockedGetConfigValue.mockReturnValue('printf "%s" "$HERMES_SECRET_KEY"');
    const hostile = "$(touch /tmp/hermes-injection-canary-should-not-exist)";
    const out = provider.get(hostile);
    // The literal string is echoed back; the subshell never ran.
    expect(out).toBe(hostile);
  });

  it("selects the requested key from a dotenv-dumping command", () => {
    mockedGetConfigValue.mockReturnValue(
      "printf 'API_SERVER_KEY=aaa\\nANTHROPIC_TOKEN=bbb\\n'",
    );
    expect(provider.get("ANTHROPIC_TOKEN")).toBe("bbb");
    expect(provider.get("API_SERVER_KEY")).toBe("aaa");
  });

  it("returns null on a non-zero exit", () => {
    mockedGetConfigValue.mockReturnValue("exit 7");
    expect(provider.get("K")).toBeNull();
  });

  it("failure log never contains helper stderr or the command string", () => {
    // Regression: execFileSync's err.message embeds the full command string
    // AND the helper's stderr — the catch blocks must log structured fields
    // (code/signal) only.
    const cmd = "printf 'STDERR_SECRET_MARKER' >&2; exit 1";
    mockedGetConfigValue.mockReturnValue(cmd);
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      expect(provider.get("K")).toBeNull();
      expect(provider.list()).toEqual({});
      expect(warnSpy).toHaveBeenCalled();
      const logged = warnSpy.mock.calls.flat().join("\n");
      expect(logged).not.toContain("STDERR_SECRET_MARKER");
      expect(logged).not.toContain(cmd);
    } finally {
      warnSpy.mockRestore();
    }
  });

  it("kills a slow helper at the timeout bound and degrades to null (no long main-process freeze)", () => {
    // Regression for the secrets-provider review (design (b)): resolution runs
    // synchronously on the Electron main process, so the helper timeout doubles
    // as the worst-case UI-freeze ceiling. A helper that blocks past the bound
    // MUST be killed and resolve to null — and do so WELL under the old 10s cap.
    // If COMMAND_TIMEOUT_MS is bumped back up (or the cap removed), this fails.
    mockedGetConfigValue.mockReturnValue("sleep 30");
    const started = Date.now();
    const out = provider.get("SLOW_KEY");
    const elapsed = Date.now() - started;
    expect(out).toBeNull();
    // Bound is 3s; allow generous spawn/teardown slack but stay far below 10s.
    expect(elapsed).toBeLessThan(6_000);
  });

  it("list() also enforces the timeout bound on a slow helper", () => {
    mockedGetConfigValue.mockReturnValue("sleep 30");
    const started = Date.now();
    const out = provider.list();
    const elapsed = Date.now() - started;
    expect(out).toEqual({});
    expect(elapsed).toBeLessThan(6_000);
  });

  it("list() returns a dotenv map from the command, {} for a bare value", () => {
    mockedGetConfigValue.mockReturnValue("printf 'A=1\\nB=2\\n'");
    expect(provider.list()).toEqual({ A: "1", B: "2" });

    mockedGetConfigValue.mockReturnValue("printf 'just-a-value'");
    expect(provider.list()).toEqual({});
  });

  it("list() omits quoted whitespace-only entries (agrees with get())", () => {
    // Greptile review on PR #644: list() stored the unquoted value without the
    // whitespace-only filter that get()/parseSecretOutput applies, so a
    // `BLANK="  "` vault placeholder showed up as a configured key in list()
    // but resolved to null on get() — the two disagreed on "is this key set?".
    // Now list() must drop BLANK while keeping the real key.
    mockedGetConfigValue.mockReturnValue(
      "printf 'REAL=value\\nBLANK=\"   \"\\n'",
    );
    const listed = provider.list();
    expect(listed).toEqual({ REAL: "value" });
    expect(listed).not.toHaveProperty("BLANK");
    // The invariant the fix enforces: list() membership matches get() resolving.
    expect(provider.get("BLANK")).toBeNull();
    expect(provider.get("REAL")).toBe("value");
  });
});
